### ISSUE TITLE
Section Headers/Footers are not animated along the cells (insert/update/delete)

### ISSUE THREAD

**Issue by bielikb** [ekazaev/ChatLayout#1]
Hi,

Im trying to integrate your ChatLayout library into an iOS project. At first, let me thank you for awesome job you did here.
Currently Im trying to structure the chat the way that:
Every message in the chat is represented as a single section in the collection view and read indicator is always shown under the latest message as a **footer** of the last message (section).

**1. Self-sizing/autolayout issue:**

Im using self-sizing cells, but I'm not sure if Im setting the correct value for estimatedSize. The self-sizing in this library works for any non-zero values, so eg setting the estimatedSize like following

```
collectionLayout.settings.estimatedItemSize = CGSize(width: 1, height: 1)
```

will display the cells, but at the same time will result in broken autolayout constraints
```
"<NSLayoutConstraint:0x600001d0e990 'UIView-Encapsulated-Layout-Height' UIView:0x7fdcbc40d8e0.height == 1   (active)>"
```

I wanted to use some general purpose estimatedSize for self-sizing cells, similar to the flow layout one:
```
UICollectionViewFlowLayout.automaticSize
```
but later realised since this is a custom collection view layout, this value is not declared.

Setting the estimated size to a concrete value, e.g. `CGSize(width: 100, height: 30)` will result in a treatment, where the cell's frame won't properly adjust as the content of the cell changes.
If you have any guidance here, Id really appreciate your help

**2. Header/Footer are not part of the animation transaction**
In my app, I want to treat the read indicator as a standalone item == not added as a subview in the cell, to gain better abstraction and to not pollute the cell with the standalone item.

Im including a sample **SwiftUI app** that leverages the _ChatLayout_ - aim of this app is to showcase the issue #1 & #2.
[ChatApp.zip](https://github.com/ekazaev/ChatLayout/files/5469682/ChatApp.zip)

Any help highly appreciated!
Thanks!

######

![Screen-Recording-2020-10-31-at-20 05 05](https://user-images.githubusercontent.com/4924709/97788189-5b520880-1bb7-11eb-8614-ac48048c33c3.gif)

**Comment by ekazaev** [comment]
@bielikb 
Thank you for your question. Ill try to explain here what is going on.

Let's start with the section question first. 

You have the next code 

```
    mutating func addSection() {
        let existingId = sections.last?.id ?? UUID().uuidString
        sections[count - 1] = Section( // New id is generated here. So it is a new section!!!
                                      header: nil,
                                      footer: nil,
                                      rows: [Row(id: existingId)])
        sections.append(Section(header: nil,
                                footer: "Read indicator",
                                rows: [Row(id: UUID().uuidString)]))

    }
```
So everytime you add a new section you also regenerate an old one and it gets a new `id`. So DifferenceKit of course generated the command to delete an old section and insert a new one. 

So when you add a new section the next commands are being sent to the collection view. I assume it is not what you expect:
[DeleteSection(0)]
[InsertSection(0), InsertSection(1)]

The commands you want are:
[ReloadSection(0)]
[InsertSection(1)]

So first of all you need to modify your code to look at least like this:
```
    mutating func addSection() {
        let existingId = sections.last?.id ?? UUID().uuidString
        sections[count - 1] = Section(id: sections[count - 1].id,
                                      header: nil,
                                      footer: nil,
                                      rows: [Row(id: existingId)])
        sections.append(Section(header: nil,
                                footer: "Read indicator",
                                rows: [Row(id: UUID().uuidString)]))

    }
```
Second thing. The `isContentEqual` for the section object is not implemented correctly:
In your example it is:
```
    public func isContentEqual(to source: Section) -> Bool {
        return id == source.id
    }
```
So basically you say to the DifferenceKit. If the ID of my section did not change, it mean it did not change at all, even if the previous one had a footer and then I deleted it in the model. You need to modify it at least like this:
```
    public func isContentEqual(to source: Section) -> Bool {
        return id == source.id  && header == source.header && footer == source.footer
    }
```

And you will get the behaviour that you expect:
![sectiondemo](https://user-images.githubusercontent.com/20243258/97812887-6e7adc00-1c7c-11eb-90b5-c56c4d3bf317.gif)

Dont forget that also from the collection point of view your footer is a brand new view. So It deletes it from the previous section of creates and adds it to the inserted section. It want move down nicely. Its a new view that belongs to the new section.

As an advice. If you suddenly see the animations you do not expect - print the changes that DifferenceKit is trying to do. You can do it in your code or you can modify the ChatLayout directly like this:
```
    /// Notifies the layout object that the contents of the collection view are about to change.
    public override func prepare(forCollectionViewUpdates updateItems: [UICollectionViewUpdateItem]) {
        print(updateItems)
       ...
```
You also need to put some thoughts when you are implementing `DifferentiableSection` and `Differentiable` protocols in your model so that DifferenceKit could correctly reflect the changes you are trying to make. That applies to any other difference library you may use as well.

**Some additional information:**
In general, Collection view threats the supplementary views in a different maner. It has an optimized animation engine only for the items. The supplementary views are being animated in the second queue. If you want them to be animated properly you should use the same approach that the Example app uses. Your "Read status" must be a cell(item) not a supplementary view. Apple's Imessage app does the same from what I can see. Basically it should not be a footer but a special service cell. 

Another thing that `ReloadSection` command doesn't behave the the way you may expect and doesn't trigger one nice animation. The section itself consist of multiple views. And reload command triggers multiple animations. I would strongly suggest you not to use sections for the purpose you are trying to use them in your example app. Or not to use them to create a date splitter for example. Collection view doesnt have a command - `reload only header` or `reload only footer`. If you want to update your supplementary views you will have to reload the whole section and most-likely you'll get the animations you don't expect.

**Comment by ekazaev** [comment]
@bielikb 
Now lets come back to the first question related to layout:
Your `ConversationCell` implementation has the next code:
```
        messageLabel.heightAnchor.constraint(equalToConstant: 35).isActive = true
        messageLabel.widthAnchor.constraint(equalToConstant: 200).isActive = true
```

But then you say to UICollectionLayout that your estimated height and width is going to be 1 pixel
```
        collectionLayout.settings.estimatedItemSize = CGSize(width: 1, height: 1)
```
So when UICollectionView starts to create or deque a cell, it asks ChatLayout "What is the size of the cell going to be". Chat layout replies that it estimates it to be CGSize(width: 1, height: 1) and it of course breakes the constraints you have inside of `ConversationCell` and you see it in the log. I asume that you have hard coded the cell size just for the demo and in the real app you wont have a hardcoded cell size. But if you do and you can not properly estimate the size - you must set such a cnostraint the priority equal to 999 so when the UICollectionView create a UIView with a wrong size - it wont break this constraint and wont polute your log with warnings.
```
2020-11-01 20:31:32.255394+0000 ChatApp[6163:111830] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003e5b750 UILabel:0x7fb6284410d0.width == 200   (active)>",
    "<NSLayoutConstraint:0x600003e5b570 H:|-(0)-[UILabel:0x7fb6284410d0]   (active, names: '|':UIView:0x7fb628441540 )>",
    "<NSLayoutConstraint:0x600003e5b5c0 UILabel:0x7fb6284410d0.trailing == UIView:0x7fb628441540.trailing   (active)>",
    "<NSLayoutConstraint:0x600003e5ba20 'UIView-Encapsulated-Layout-Width' UIView:0x7fb628441540.width == 100   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003e5b750 UILabel:0x7fb6284410d0.width == 200   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-11-01 20:31:32.256537+0000 ChatApp[6163:111830] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003e5b610 UILabel:0x7fb6284410d0.height == 35   (active)>",
    "<NSLayoutConstraint:0x600003e5b340 V:|-(0)-[UILabel:0x7fb6284410d0]   (active, names: '|':UIView:0x7fb628441540 )>",
    "<NSLayoutConstraint:0x600003e5b520 UILabel:0x7fb6284410d0.bottom == UIView:0x7fb628441540.bottom   (active)>",
    "<NSLayoutConstraint:0x600003e5ba70 'UIView-Encapsulated-Layout-Height' UIView:0x7fb628441540.height == 30   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003e5b610 UILabel:0x7fb6284410d0.height == 35   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```
Same applies to `CGSize(width: 100, height: 30)`. The UIView itself will be created by the `UICollectionView` with the size that breaks the constraints within your cell.

**Comment by bielikb** [comment]
Hi @ekazaev, 
thanks for a thorough explanation!
As you properly stated out, this is just a proof of concept/sample, usage of hardcoded sizing constants is not intended.

**Animating the sections:**
I followed your suggestions and I did get rid of the footers/headers from the cells. In the updated version of the sample app, they're represented as standalone cells for a given section.
```
struct Section: Hashable {

    let id: String
    let header: Row?
    let footer: Row?
    private(set) var rows: [Row] = []

    let cells: [Row]
    ....
}
```

Thank for pointing the issues around the diffing.  I updated the diffing conformance in the Sample to follow the auto-computed conformance for `Equatable` protocol:
```
    public func isContentEqual(to source: Section) -> Bool {
        return self == source
    }
```

The bit that I had to get my head wrap around was actually the `DifferentiableSection` initializer. Im not sure I provided the correct implementation for that, yet for inserting the new sections it looks like it works fine:
```
    public init<C: Swift.Collection>(source: Section, elements: C) where C.Element == Row {
        self.init(header: nil, footer: nil, cells: Array(elements))
    }
```
![Screen-Recording-2020-11-02-at-15 28 23](https://user-images.githubusercontent.com/4924709/97879545-6a07ff00-1d20-11eb-800b-62c89a67b567.gif)

**Fatal Error:**
I have one following question:

One thing I noticed with this implementation is that in scenario:
Given I added couple of sections to collection view
when I hit the reload button
and then I hit the add section button
the `StateController` gets out-of-sync and `fatalError("Internal inconsistency")` in StateController.swift` on line 220 is fired.

Here's the updated version of the Sample App. I think Im pretty close to what Im looking for now.
[ChatApp_updated.zip](https://github.com/ekazaev/ChatLayout/files/5475573/ChatApp_updated.zip)

Thanks for your time!
Best,
Boris

**Comment by ekazaev** [comment]
Hi, @bielikb 

I have noticed that as well and it was fixed in todays update. Basically the reloaded cell counter was never emptied after animation. I probably lost it at some point.

Please, update your `ChatLayout` Version to the latest one. The issue should be fixed there.

Regards,
Eugene.

**Comment by ekazaev** [comment]
@bielikb  If I can give you another advice - do not use sections at all. There are some natural limitations within the collection view. One of them, for example, you can not move the cell in to the section that is being moved or reloaded, the collection view will crash. This statement is valid for every UICollectionViewLayout. So, DifferenceKit splits those type of updates into steps to avoid such situations, so it first moves the section and them moves an item into that section, or vise versa. But visually in may not be what you expect. If you get rid of sections completely youll probably wont even face such situation. 
From the understanding I got during the development - sections can be something relatively static, where the most of modifications happen within the section itself. So I just got rid of them both in the example app and in our product app. Never regretted it.

**Comment by ekazaev** [comment]
@bielikb Also I noticed in your updated app that after you changed footer to be a cell you provide wrong amount of items in the section. It leads to the crash.

**Comment by ekazaev** [comment]
@bielikb Also there is still a problem with the model. When you add a new section there are 4! calls being made:
[DeleteItem(0), DeleteItem(0,1)]
[InsertSection(1)]
[InsertItem(0,0)]
[ReloadSection(1)]

**Comment by ekazaev** [comment]
@bielikb I am closing the issue. But Do not hesitate to ask if you'll have any other questions
