### ISSUE TITLE
Screen flickering when moving from landscape to portrait

### ISSUE THREAD

**Issue by Cristiane-Burlamaqui** [ekazaev/ChatLayout#12]
**Steps:**

Send and receive messages
Move the phone to landscape
Move it back to portrait

**Expected result:**

Moving to portrait without flickering

**Actual result:**

Conversation flickers when moving to portrait

https://user-images.githubusercontent.com/78358306/110513884-a00a2500-80fe-11eb-9158-e7eaacec15a1.MP4

**Comment by ekazaev** [comment]
@Cristiane-Burlamaqui I had another look into an issue you created. Can you provide more details as the jump that you have is too big for the reason I described above. I can not reproduce it. But, you need to keep in mind, that if rotation happens while UICollectionView is updating - there is no way to stop it and calculate the correct offset in principle. So you may see some jumps like in this gif on the second rotation. 

![RPReplay_Final1619017377](https://user-images.githubusercontent.com/20243258/115576938-e1741f80-a2bb-11eb-90ce-683c844899db.gif)

But it the real life chat updates happen rarely, and as I said above - same small correction happens even in iMessage
![imessage](https://user-images.githubusercontent.com/20243258/115578064-da99dc80-a2bc-11eb-9a32-6ea45579c047.gif)

Also have a look at the latest version of the Example app. Some updates have been made since

**Comment by Cristiane-Burlamaqui** [comment]
Hello @ekazaev to reproduce the issue you have to stop load initial messages and comment out the ChatViewController class' line 153 `currentInterfaceActions.options.insert(.changingFrameSize)`, because it is only present on the example code and not in the ChatLayout's public API.
After those changes you'll see the gap between last message position and the message composer when you rotate from landscape to portrait mode and the flickering when the correct position is calculated.

**Comment by ekazaev** [comment]
@Cristiane-Burlamaqui I see what you are talking about. But this is exactly the resposibility of the host app. ChatLayout knows nothing about elements you have in your app and can not compensate their behaviour. As a layout itself it can not know that keyboar appeared for instance. It should be handled by the host app.

I can reproduce it with the changes you suggested - but there is nothing to fix from the layout point of view. 
https://user-images.githubusercontent.com/20243258/115795406-c8589500-a3c7-11eb-9f35-5a8d22e659d1.MP4
ChatLayout doesnt know that you have an input view or your view controller can become first responder. Host app deals wit it. 

Comment out those lines
```
    override var inputAccessoryView: UIView? {
        return inputBarView
    }

    override var canBecomeFirstResponder: Bool {
        return true
    }
```
And you will see that with suggested changes ChatLayout calculates offsets correctly:
https://user-images.githubusercontent.com/20243258/115795593-18375c00-a3c8-11eb-88b6-da8e0c66a8a5.MP4
(It is important to say that you may still see little jump but it is related that as its an IPhone 13 - safeArea changes the insets of the collection view but it happens after the rotation started and it is also should be handled by the host application)
