### ISSUE TITLE
Combine multiple images and text in a single bubble

### ISSUE THREAD

**Issue by saqibdb** [ekazaev/ChatLayout#15]
Hello, the pod works beautifully and controls are very good as well.
But I am wondering if there is any possible way to combine multiple images and text in a single bubble

![image](https://user-images.githubusercontent.com/5718485/115412147-8388fe80-a20d-11eb-8d11-c1971899dd15.png)

**Comment by ekazaev** [comment]
@saqibdb Thank you very much. Of course it is possible. You just need to implement it the way you like. For example use the current image cell in the example app and propagate there 4 images instead of 1. I would also recommend to optimize image sizes to that rendering of said images would be seamless

**Comment by saqibdb** [comment]
Allright, yes got it..... Thanks

For anyone using the example, go to ImageView.swift and make multiple imageViews to incorporate the results
