### ISSUE TITLE
How to implement UICollectionView inside UICollectionViewCell right way?

### ISSUE THREAD

**Issue by hhoangna** [ekazaev/ChatLayout#44]
Hi @ekazaev! Thanks for your great pod. It's work perfect and very helpful with me
Everything is OK with custom view. But i have a problem when i make a custom view with UICollectionView auto layout inside.
I want to add a collectionview dynamic height inside and height off collectionview cell based on collectionview content height.
And the problem is the first load height of collectionview cell not correct. I need reload several times to get correct height of collectionview cell.
Please support me to get correct collection view height inside collectionview cell.

**Comment by ekazaev** [comment]
@hhoangna Hi.

You chose a hard task to achieve but I am sure it is possible. I can only direct you where to look at. Basically the Main collection view will measure the cell directly after you return it `func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell`. You need to write the code of your cell with the collection inside in a way so that when the cell is created and populated with the data - you will know the height of the internal collection in the cell and could either set the height constraint of the cell - or return the desired cell size from `func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes` in the `UICollectionViewCell`. What may point you into a right direction is `TextMessageView`. Check the commented `func preferredLayoutAttributesFitting(_ layoutAttributes: ChatLayoutAttributes) -> ChatLayoutAttributes?` function there. Implement similar in your cell with the collection so when the `UICollectionViewLayout` asks for a preferred size - you'll be able to return it based on the content of the collection view inside of the cell.

**Comment by ekazaev** [comment]
Feel free to reopen this issue if youll have questions

**Comment by hhoangna** [comment]
Hi @ekazaev. So sorry about reopening this issue. 
I had try to set new size of cell in function `func preferredLayoutAttributesFitting(_ layoutAttributes: ChatLayoutAttributes) -> ChatLayoutAttributes?`
But it still not working smooth. It's wrong in the first load. This is my code for UICollectionView in UICollectionViewCell
Please review and show to me my mistake. 
Can you give me a tutorial project? 
Thanks so much

[SGIComponentActionView.swift.zip](https://github.com/ekazaev/ChatLayout/files/10853873/SGIComponentActionView.swift.zip)
