### ISSUE TITLE
 The message list will shake.

### ISSUE THREAD

**Issue by std-s** [ekazaev/ChatLayout#50]
@ekazaev Hi,
In the case of keyboard activation, after the preview disappears, the message list will shake.

version: 1.3.0

https://github.com/ekazaev/ChatLayout/assets/99468005/a8d29023-1a6d-40f4-939a-6e585cb20484

**Comment by ekazaev** [comment]
Hi @std-s  

Thanks for the question. And what is the problem with it? It is the matter of the keyboard handling rather than the library itself.

**Comment by ekazaev** [comment]
@std-s I understand how to reproduce it. I don’t really understand why it bothers you. In the real life application you dont have constant appearance of the new messages and typing indicators. It is done in the example app for the imitation. Disable typing and new messages in the example app (RandomDataSource) and you wont see it the same as on the video i attached above. 

If disabling typing and new messages appearance fixes it - it suggests that not submitting changes to the Collection View datasource while the preview is shown should fix this visual issue. But I have to point out again - it is not the library issue. It needs to be fixed in the hosting app code. 

When I have time I will look at it (even though I think it is not something bothering) but I can’t guarantee when. Hope that the suggestion above will help you to resolve that issue yourself in case it bothers you.

**Comment by ekazaev** [comment]
@std-s Having a quick look I have more information to share. It seems that it is yet another hello from Apple and I have the feeling that it appeared in the recent IOS versions. Sometimes (not always) the app is receiving the incorrect original position of the keyboard when the preview is disappearing, and then it receives the correct one as well. What you can do is delay the removal of the `.showingPreview` for a few milliseconds and then filtering it out to avoid the incorrect keyboard position value in `keyboardWillChangeFrame` using `!currentInterfaceActions.options.contains(.showingPreview)`.

**Comment by std-s** [comment]
okay ,i'll give it a try.
