### ISSUE TITLE
Performance when push to ChatViewController not good

### ISSUE THREAD

**Issue by hhoangna** [ekazaev/ChatLayout#51]
Hi @ekazaev!
I used to apply ChatLayout to my ChatViewController. When push from list conversations to ChatViewController screen, i think i have a problem. It seem a little slow to show messages in Chat screen. I have run Time Profile by Instruments. I don't know why there functions and classes get more time. 

https://github.com/ekazaev/ChatLayout/assets/26923574/b49611ab-250a-4f1e-b574-572974d517c1

<img width="477" alt="image" src="https://github.com/ekazaev/ChatLayout/assets/26923574/2839e359-5f24-485f-84fc-7140ef8e99a3">
<img width="1220" alt="image" src="https://github.com/ekazaev/ChatLayout/assets/26923574/dc78bbc9-f31b-4e4b-b9c9-80d6b4477927">

**Comment by ekazaev** [comment]
Hi @hhoangna

In general there is nothing wrong with those functions. You are actually initialising a lot of views in one go. Potentially your `ChatReplyCell` worth having a look though. It seems to be the heaviest one. But there is nothing to do with the library itself.

I see you also have a flickering when chat view is being pushed to the `UINavigationController` - if you want to get rid of it - you need to setup collection first time in the first call of `viewDidLayoutSubviews`

**Comment by hhoangna** [comment]
I try to setup collection in viewDidLayoutSubviews but nothing change :(
I know that a lot of views initial but i think they are nessessory.

**Comment by ekazaev** [comment]
@hhoangna Lets first try to understand straight what are you doing. Are you trying to fix some performance issue related to the amount of the views you are creating or the visual glitch that the chat doesn’t appear immediately when the chat controller is being pushed into navigation controller and blame it on performance?

If you are trying to solve the visual glitch - then I can point you to the core of the problem. You are trying to update the collection view while it is being in the Core Animation transaction initiated by the animated push into the navigation controller. To avoid it you need to correctly set it in viewDidLayoutSubviews without triggering extra animation curve. The Instruments wont help you there. 

On other hand, If you are trying to solve just some performance issue in general - I can not help you there. It is your code, I am not familiar with it. I can only assure you that it is doable as I have seen the apps in production that use ChatLayout without visible performance issues.

**Comment by hhoangna** [comment]
Yup. Still a lot of issues with my app. Such as animation while push to chat screen. I can't find any code line make that animation.
Can we add contact each other? I will sent you my source code to preview.

**Comment by ekazaev** [comment]
@hhoangna I appreciate the honour but Id prefer to avoid such a close interaction unless it is going to be a paid service. I have my own work to do otherwise.

But I assure you that what I said above that what is happening is that you are creating an extra animation loop while the controller is being pushed into the UINavigationController. Check that you propagate the first data within the viewDidLayoutSubviews. If your code is losely based on the Example app check that in this piece at this moment you return true

```swift
collectionView.reload(using: changeSet,
                                  interrupt: { changeSet in
                                      guard changeSet.sectionInserted.isEmpty else {
                                          return true // FIRST TIME YOU MUST RETURN TRUE TO AVOID IT GOING TO performBatchUpdates
                                      }
                                      return false
                                  }
```

**Comment by hhoangna** [comment]
I have fixed animation when push Navigation Controller. It's a animation default of system when push from tabbarController.selectedViewController.navigationController.push(vc, animation: true), then have no animation now.

The first load data in my code is same as your Example 
`collectionView.reload(using: changeSet,
                                  interrupt: { changeSet in
                if shouldInterrupt {
                    return true
                } else {
                    if self.currentControllerActions.options.contains(.loadingInitialMessages) {
                        guard changeSet.sectionInserted.isEmpty else {
                            return true
                        }
                        return false
                    } else {
                        return false
                    }
                }
            }`

Nothing change, i think all problem is from initialing more subviews in custom chat cell

**Comment by ekazaev** [comment]
@hhoangna Can you put a breakpoint inside of `onInterruptedReload` and make sure that when view controller is just starts to be pushed into a UINavigationController? 
As I said. YOu are initialising views in the main thread. So it can create a delay but not a flickering ui. Your problem is the animation transition.

**Comment by hhoangna** [comment]
Thanks you so much. I'll try

**Comment by ekazaev** [comment]
@hhoangna Good luck

**Comment by hhoangna** [comment]
Hi there :D 
Sorry because of reopen this issue

I had try create new synchronously function to get data and binding to collection view. And put them in  viewDidLayoutSubviews. It's working, flickering was removed. But it's seem to get more time before navigation push to chat screen (about ~ 500ms)
And they have weird animation like video below:

https://github.com/ekazaev/ChatLayout/assets/26923574/7ce2f80c-a1ae-45d4-bab5-cb0824b1cfa9

I don't know why. Then i crop a part of my project source code to sent to you. This can not run. Please review code and give me some advices. Thanks you so much
[Chat.zip](https://github.com/ekazaev/ChatLayout/files/11737445/Chat.zip)

**Comment by ekazaev** [comment]
@hhoangna I will have a look later at your code. But I still have the feeling that there is some unexpected animation happens during the push. Check it out. 

But I can tell you where is the delay can happen. 
First place that can cause the delay - measure your synchronious function how long does it take to convert your data model to cell model. 
Second, potentially you have heavy cells and because there is quite a few of them on the screens - their structure may require optimisation.

This is the case that you need to check in the Instruments
