### ISSUE TITLE
How to use ChatLayout in SwiftUI project?

### ISSUE THREAD

**Issue by zoujiaqing** [ekazaev/ChatLayout#65]

**Comment by ekazaev** [comment]
@zoujiaqing  You can try to wrap it into `UIViewRepresentable` but you wont be able to have enough control over there due to SwiftUI <-> UIKit interoperability limitations. I would suggest you to implement the entire chat using UIKit including the keyboard handling and so on. But then you technically can integrate it into a SwiftUI app without limitations.

**Comment by ekazaev** [comment]
@zoujiaqing Ill close the issue - feel free to reopen it if needed.
