### ISSUE TITLE
Seeking help about keepContentOffsetAtBottomOnBatchUpdates

### ISSUE THREAD

**Issue by JoakimLiu** [ekazaev/ChatLayout#69]
hi @ekazaev , thank you for making such a great library! But I have a problem and need your help.

## context
When content of the Collectionview Cell changes, then the height changes, the call `reload` method will cause the Collection to move up, just like `URLView` in the demo, here is the effect of the video I recorded, notice the change in the content of `youtube.com` url at video 4s.

https://github.com/ekazaev/ChatLayout/assets/7654983/83e7221f-63cb-44ee-b55a-0a50f331a433

##  goals and attempts
I want the content to move down when it‘s content height changes.  Like the video below after I tried to change the code,

https://github.com/ekazaev/ChatLayout/assets/7654983/b8d18d35-dd42-4dda-8e83-bc5440349172

For the changed code, please see https://github.com/JoakimLiu/ChatLayout/commit/97268284640120ca2d261dc3f47662e44d1fc7b4

## help
Do you have a better way to accomplish this?

**Comment by ekazaev** [comment]
@JoakimLiu 

I dont fully understand the question probably. If you set the `keepContentOffsetAtBottomOnBatchUpdates` to `false` and and call reload - doesn't it give you expected effect? 

https://github.com/ekazaev/ChatLayout/assets/20243258/9b828dad-856e-49b7-a323-13b61f32306c

Please note that ChatLayout in general is build expecting that this flag is enabled, but some cases like when you load messages below, or like the one you have - you can temporary disable it.

**Comment by JoakimLiu** [comment]
@ekazaev  Thank you for your reply.

The `disabled.flag.mp4` is my expected effect,  but other scenarios I still need `keepContentOffsetAtBottomOnBatchUpdates = true` to keep the current content at the bottom of the visible.

Uh,  Why am I asking this? It's because I'm having a problem with message localization. The scenario is that when I come in ChatViewController and locate message A which at the top of the visible area,  if that message A is followed by URLView message B,  when message B is reload after loaded the data, it will move up, resulting in message A not being in the visible area.

https://github.com/JoakimLiu/ChatLayout/commit/97268284640120ca2d261dc3f47662e44d1fc7b4  is my current solution code, but I don't think it's elegant enough, so I'm asking if you have a better solution.

**Comment by ekazaev** [comment]
@JoakimLiu So, basically what you say that the flag works as expected. The fact that cell when it grows pushes the content up is also a correct behaviour. You have a special case you want to handle. So I suggest you to do in on another side rather than changing the ChatLayout. You need to add some logic to the `process` function in the example app, that analyses the `changeSet`. And if it contains no insertions/deletions and only reloads/reconfigures, and it is the case when you want to keep the top cell - set this flag to false before `reload(using: changeSet` and enable it back in the `completion`. This is how I solve such cases.

**Comment by JoakimLiu** [comment]
@ekazaev Okay. Thank you.
